name: first-workflow

on: [push]

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Hello World"
            - run: echo "Hello World 2"
            - run: echo "Hello World 3"
            