name: 01-basics-workflows

on: 
    workflow_dispatch

jobs:
    print-hello-world:
        runs-on: ubuntu-latest
        steps:
            - name: Print Hello World
              run: echo "Hello World 2"